# Generated by Django 3.1.2 on 2020-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, upload_to='images/review'),
        ),
    ]
