# Generated by Django 3.1.2 on 2020-10-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=40)),
                ('recipe_image', models.ImageField(blank=True, upload_to='images/Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_birth_year', models.IntegerField(default=0)),
                ('user_birth_month', models.IntegerField(default=0)),
                ('user_birth_day', models.IntegerField(default=0)),
                ('userid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
